Add image-to-text model implementation
UppuluriKalyani/ML-Nexus pull request #63
Opened 2024-10-02 17:07 UTC by BhavyaFattania

I have added requirements.txt and a streamlit app code
the requirements.txt contains all the necessary packages and process to run the code.

2024-10-03 07:33 UTC, UppuluriKalyani requested changes
@BhavyaFattania please keep those files in a folder  name:image to text model  under computer vision folder and also put results 
Readme file....share the screenshots of results.

2024-10-03 18:00 UTC, UppuluriKalyani commented
> for screenshot I have uploaded in results file, It is showing file cannot read. I have uploaded jpg image but it says code editor can't read file format

Maybe network problem try again after some time

2024-10-04 17:27 UTC, SaiNivedh26 requested changes
All are good. But the documentation needs to be refined

2024-10-05 20:25 UTC, SaiNivedh26 approved these changes

2024-10-05 20:26 UTC, merged